end2end_eval:
  metrics:
    text_block:
      metric:
        - Edit_dist
        # - BLEU
        # - METEOR
    display_formula:
      metric:
        - Edit_dist
        - CDM_plain  # CDM can be calculated directly by calling CDM in config file if you have CDM environment
    table:
      metric:
        - TEDS
        - Edit_dist
    reading_order:
      metric:
        - Edit_dist
  dataset:
    dataset_name: end2end_dataset
    ground_truth:
      data_path: /mnt/disk1/chenkehao/parsing_bench_data/OmniDocBench.json
    prediction:
      data_path: /mnt/disk1/chenkehao/parsing_bench_data/infer_output/mineru_vlm
    match_method: quick_match
    # filter: 
    #   language: english
